# install ubuntu 24.04
# from <image name>
# tim trong local -> neu co dung luon
# chua co
#   -> cloud (dockerhub, aws ecr ...)
FROM my-image:latest

WORKDIR /index

COPY ./web /index

CMD ["npm", "run", "dev"]